openapi: 3.0.0
info:
  version: '1.0'
  title: "Discoveroo"
  description: TODO description
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
servers:
  - url: https://discoveroo.herokuapp.com/api/v1

paths:

  /authentication:
    post:
      description: >-
        Authenticates an existing user
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '302':
          description: User authenticated successfully
          headers:
            Location:
              schema:
                type: string
                format: url
        '401':
          description: User authentication not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                
  /users:
    get:
      description: >-
        TODO
      summary: Fetch user info
      parameters:
        - in: query
          name: email
          schema:
            type: string
            format: email
          required: false
          description: e-mail address of user to find
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
    post:
      description: >-
        TODO
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
      responses:
        '201':
          description: TODO
        '404':
          description: TODO
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Descriptive, human-readable,  error message
                    type: string
                    
  /users/me:
    get:
      description: >-
        TODO
      summary: Fetch logged in user info
      security:
        - CookieAuth: []
        - HeaderAuth: []
        - QueryAuth: []
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                
                  
  /users/{username}:
    get:
      description: >-
        TODO
      summary: TODO
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: username of the user to fetch
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                
    
  /upload:
    post:
      description: >-
        TODO
      summary: Upload a new post
      security:
        - CookieAuth: []
        - HeaderAuth: []
        - QueryAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadRequest'
      responses:
        # TODO should be 201?
        '200':
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
  
  /upload/{postID}:
    get:
      description: >-
        TODO
      summary: Get uploaded post
      parameters:
        - in: path
          name: postID
          required: true
          schema:
            type: string
          description: ID of the post to fetch
      responses:
        # TODO should be 201?
        '200':
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
                
  /gallery:
    get:
      description: >-
        TODO
      summary: Get uploaded pictures
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  
  /follow/{username}:
    get:
      description: >-
        TODO
      summary: Follow/unfollow a user
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: username of the user to follow
      security:
        - CookieAuth: []
        - HeaderAuth: []
        - QueryAuth: []
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowResponse'
        '400':
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowResponse'
  
  /comment:
    post:
      description: >-
        TODO
      summary: Make a new comment on a post
      security:
        - CookieAuth: []
        - HeaderAuth: []
        - QueryAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentResponse'
                
  /comment/{commentID}:
    get:
      description: >-
        TODO
      summary: Fetch a comment
      parameters:
        - in: path
          name: commentID
          required: true
          schema:
            type: string
          description: ID of the comment to fetch
      security:
        - CookieAuth: []
        - HeaderAuth: []
        - QueryAuth: []
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  comment:
                    type: string

  /vote/{ID}:
    post:
      description: >-
        TODO
      summary: Vote a post/comment
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
          description: ID of the comment/post to upvote
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: Decides whether ID refers to a comment or a post
                vote:
                  type: number
                  description: \>0 to upvote, <0 to downvote
      security:
        - CookieAuth: []
        - HeaderAuth: []
        - QueryAuth: []
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  change:
                    type: number
                  total:
                    type: number
                    
  /image/{filename}:
    get:
      description: >-
        TODO
      summary: Fetch an image (posts images)
      parameters:
        - in: path
          name: filename
          required: true
          schema:
            type: string
          description: Filename of the image to retrieve
      responses:
        '200':
          description: TODO
          content:
            image/jpeg:
            
  /coupon/{username}/{points}:
    get:
      description: >-
        TODO
      summary: Get discount coupon
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: Username
        - in: path
          name: points
          required: true
          schema:
            type: number
          description: points
      responses:
        '200':
          description: TODO
          content:
            image/jpeg:

components:
  
  schemas:
  
    AuthenticationResponse:
      type: object
      # TODO 'required' field
      properties:
        success:
          type: boolean
        message:
          type: string
        token:
          type: string
          format: jwt
        email:
          type: string
          format: email
        id:
          type: string
        self:
          # TODO what is self?
          type: string
      
    UserResponse:
      type: object
      properties:
        self:
          type: string
        email:
          type: string
          format: email
    
    NewUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
          format: password
      required:
        - email
        - username
        - password
    
    UploadRequest:
      type: object
      properties:
        myFile:
          type: string
          format: binary
        title:
          type: string
      required:
        - myFile
        - title
    
    UploadResponse:
      type: object
      # TODO 'required' field
      properties:
        status:
          type: string
        path:
          type: string
    
    FollowResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
          
    CommentRequest:
      type: object
      # TODO 'required' field
      properties:
        comment:
          type: string
        postId:
          type: string
    
    CommentResponse:
      type: object
      # TODO 'required' field
      properties:
        success:
          type: boolean
        location:
          type: string
    
    Post:
      type: object
      properties:
        user:
          type: object
          properties:
            username:
              type: string
            email:
              type: string
              format: email
        picture_name:
          type: string
        picture_path:
         type: string
        time:
          type: integer
          description: Post upload time (timestamp, in milliseconds)
        title:
          type: string
        text:
          type: string
        votes:
          $ref: '#/components/schemas/votes_compact'
        comments:
          $ref: '#/components/schemas/comments_compact'
    
    votes_compact:
      type: object
      properties:
        likes:
          type: array
          items:
            type: string
            format: id
        dislikes:
          type: array
          items:
            type: string
            format: id
    
    comments_compact:
          type: array
          items:
            type: string
            format: id
  
  securitySchemes:
    
    CookieAuth:
      type: apiKey
      in: cookie
      name: token
    
    HeaderAuth:
      type: apiKey
      in: header
      name: x-access-token
      
    QueryAuth:
      type: apiKey
      in: query
      name: token