openapi: 3.0.0
info:
  version: '1.0'
  title: "Discoveroo"
  description: TODO description
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
  servers:
    - url: https://TODO.com/api/v1
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json

paths:

  /authentication:
    post:
      description: >-
        Authenticates an existing user
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        302:
          description: User authenticated successfully
          headers:
            Location:
              schema:
                type: string
                format: url
        401:
          description: User authentication not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    emum:
                      - false
                  message:
                    type: string
                
  /users:
    get:
      description: >-
        TODO
      summary: Fetch user info
      parameters:
        - in: query
          name: email
          schema:
            type: string
            format: email
          required: false
          desctiption: e-mail address of user to find
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
    post:
      description: >-
        TODO
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
      responses:
        201:
          description: TODO
        404:
          description: TODO
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Descriptive, human-readable,  error message
                    type: string
                    
  /users/me:
    get:
      description: >-
        TODO
      summary: Fetch logged in user info
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                
                  
  /users/{username}:
    get:
      description: >-
        TODO
      summary: TODO
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                
    
  /upload:
    post:
      description: >-
        TODO
      summary: Upload a new post
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadRequest'
      responses:
        # TODO should be 201?
        200:
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
  
  /upload/{postID}:
    get:
      description: >-
        TODO
      summary: Get uploaded post
      parameters:
        - in: path
          name: postID
          required: true
          schema:
            type: string
          description: ID of the post
      responses:
        # TODO should be 201?
        200:
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
                
  /gallery:
    get:
      description: >-
        TODO
      summary: Get uploaded pictures
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  
  /follow/{username}:
    get:
      description: >-
        TODO
      summary: Follow/unfollow a user
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowResponse'
        400:
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowResponse'


components:
  schemas:
  
    AuthenticationResponse:
      type: object
      # TODO 'required' field
      properties:
        success:
          type: boolean
        message:
          type: string
        token:
          type: string
          format: jwt
        email:
          type: string
          format: email
        id:
          type: string
        self:
          # TODO what is self?
          type: string
      
    UserResponse:
      type: object
      properties:
        self:
          type: string
        email:
          type: string
          format: email
    
    NewUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
          format: password
      required:
        - email
        - username
        - password
    
    UploadRequest:
      type: object
      properties:
        myFile:
          type: string
          format: binary
        title:
          type: string
      required:
        - myFile
        - title
    
    UploadResponse:
      type: object
      # TODO 'required' field
      properties:
        status:
          type: string
        path:
          type: string
    
    FollowResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    
    Post:
      type: object
      properties:
        user:
          type: object
          properties:
            username:
              type: string
            email:
              type: string
              format: email
        picture_name:
          type: string
        picture_path:
         type: string
        time:
          type: integer
          description: Post upload time (timestamp, in milliseconds)
        title:
          type: string
        text:
          type: string
        votes:
          $ref: '#/components/schemas/votes_compact'
        comments:
          $ref: '#/components/schemas/comments_compact'
    
    votes_compact:
      type: object
      properties:
        likes:
          type: array
          items:
            type: string
            format: id
        dislikes:
          type: array
          items:
            type: string
            format: id
    
    comments_compact:
          type: array
          items:
            type: string
            format: id